services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    command: ["start-dev"]
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8080:8080
    # volumes:
      # - ./realm-export.json:/tmp/realm-export.json
 
networks:
  default:
    name: enei-website_sail
    external: true

